---
- name: Removes a cluster from the AI Service and Libvirt/KVM
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes

  vars:
    cluster_id: ""
    cluster_status: ""
    deployment_name: ""
    compiled_uri_headers:
      User-Agent: AnsibleAutomation/4.2
    delete_generated_assets: true

  tasks:
    - name: Read in variables
      include_vars:
        dir: vars
        extensions:
          - 'yaml'
          - 'yml'

    - name: Preflight Checks
      include_tasks: tasks/preflight.yaml

    - name: Set up Authentication Headers if needed
      include_tasks: tasks/ai_svc_setup_auth_headers.yaml
      when: assisted_service_authentication != "none"

    - name: Read AI Service, check for existing cluster
      uri:
        headers: "{{ compiled_uri_headers }}"
        url: "{{ assisted_service_endpoint }}/clusters"
        return_content: yes
        method: GET
      register: read_clusters
    
    - name: Set facts if cluster exists
      set_fact:
        cluster_id: "{{ item.id }}"
        cluster_status: "{{ item.status }}"
      loop: "{{ read_clusters.json }}"
      when: (item.base_dns_domain == cluster_domain) and (item.name == cluster_name)

    - name: Delete the cluster from the Assisted Installer service
      block:
      - name: Cancel the cluster just in case
        uri:
          headers: "{{ compiled_uri_headers }}"
          url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}/actions/cancel"
          return_content: yes
          method: POST
          status_code: 202
          body_format: json
        register: cancel_cluster
        ignore_errors: yes

      - name: Reset the cluster just in case
        uri:
          headers: "{{ compiled_uri_headers }}"
          url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}/actions/reset"
          return_content: yes
          method: POST
          status_code: 202
          body_format: json
        register: reset_cluster
        ignore_errors: yes

      - name: Delete the cluster
        uri:
          headers: "{{ compiled_uri_headers }}"
          url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}"
          return_content: yes
          method: DELETE
          status_code: 204
          body_format: json
        register: delete_cluster
        ignore_errors: yes
      when: cluster_id != ""

    - name: Delete the VMs in Prism
      block:

      - name: Delete per VM instance
        include_tasks: tasks/nutanix_destroy_vms.yaml
        loop: "{{ cluster_nodes }}"
        loop_control:
          label: "Destroying {{ cluster_name }}-{{ node.name }}"
          loop_var: node

      - name: Delete the AI ISO
        block:
        - name: Get list of images
          uri:
            url: "{{ nutanix_prism_endpoint }}{{ nutanix_prism_api_v3_base }}/images/list"
            return_content: yes
            method: POST
            status_code: 200
            body_format: json
            body: '{"kind":"image", "filter": "name==ocp-ai-{{ cluster_id }}"}'
            force_basic_auth: yes
            user: "{{ nutanix_prism_username }}"
            password: "{{ nutanix_prism_password }}"
            validate_certs: "{{ not nutanix_prism_skip_ssl_verification|bool }}"
          register: nutanix_images_info

        - name: Set Image UUID
          set_fact:
            nutanix_ocp_ai_iso_uuid: "{{ image.metadata.uuid }}"
          when: image.spec.name == "ocp-ai-{{ cluster_id }}"
          loop: "{{ nutanix_images_info.json.entities }}"
          loop_control:
            loop_var: image

        - name: Delete Image if it exists
          uri:
            url: "{{ nutanix_prism_endpoint }}{{ nutanix_prism_api_v3_base }}/images/{{ nutanix_ocp_ai_iso_uuid }}"
            return_content: yes
            method: DELETE
            status_code: 202
            body_format: json
            force_basic_auth: yes
            user: "{{ nutanix_prism_username }}"
            password: "{{ nutanix_prism_password }}"
            validate_certs: "{{ not nutanix_prism_skip_ssl_verification|bool }}"
          when: nutanix_ocp_ai_iso_uuid is defined

      - name: Delete the generated content directory
        file:
          state: absent
          path: "{{ generated_asset_directory }}/{{ cluster_id }}/"
        when: delete_generated_assets|bool and cluster_id != ""