---
# tasks file for ocp4-nutanix-csi
- name: Create {{ operator_namespace }} namespace
  k8s:
    state: present
    kind: Namespace
    api_version: v1
    merge_type:
    - strategic-merge
    - merge
    definition:
      metadata:
        name: "{{ operator_namespace }}"
        annotations:
          openshift.io/description: "Resources for the Nutanix CSI Operator"
          openshift.io/display-name: "Nutanix CSI Operator"
      spec: {}
  tags:
  - preflight
  - create_ns
  register: k8s_run
  until: k8s_run is not failed
  delay: 10
  retries: 30

- name: Create Operator OperatorGroup
  k8s:
    state: present
    apply: yes
    definition: "{{ lookup('template', template_file ) | from_yaml }}"
  loop:
  - ./templates/operatorgroup.yaml.j2
  loop_control:
    loop_var: template_file
  until: k8s_run is not failed
  delay: 10
  retries: 30

- name: Create Operator subscription
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', template_file ) | from_yaml }}"
  loop:
  - ./templates/subscription.yaml.j2
  loop_control:
    loop_var: template_file
  until: k8s_run is not failed
  delay: 10
  retries: 30

- name: Wait for the CSI Operator to come online
  k8s_info:
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: nutanixcsistorages.crd.nutanix.com
  register: csi_crd
  retries: 200
  delay: 10
  until: csi_crd.resources | list | length == 1

- name: Create Secret, Operand instance, and StorageClass
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', template_file ) | from_yaml }}"
  loop:
  - ./templates/secret.yaml.j2
  - ./templates/instance.yaml.j2
  - ./templates/storageclass-volumes.yaml.j2
  loop_control:
    loop_var: template_file
  until: k8s_run is not failed
  delay: 10
  retries: 30