---
# nutanix_prism_hostname: The IP or Hostname of your Prism Element instance
nutanix_prism_hostname: ahv-rocinante-cvm.kemo.labs
# nutanix_prism_port: The port Prism is accessible from
nutanix_prism_port: 9440

# nutanix_prism_skip_ssl_verification disables SSL Certificate Chain Verification when enabled
nutanix_prism_skip_ssl_verification: true

# nutanix_prism_authentication_type: Currently supports `basic` username/password
nutanix_prism_authentication_type: basic
nutanix_prism_username: admin
nutanix_prism_password: Passw0rd123!

# nutanix_prism_cluster_name is the name of the network the OpenShift VMs will be attached to
nutanix_prism_cluster_name: MyCluster

# nutanix_prism_network_name is the name of the network the OpenShift VMs will be attached to
nutanix_prism_network_name: MyLAN

# nutanix_prism_vm_storage_container_name is the name of the Storage Container the OpenShift VMs will use for their Disks
nutanix_prism_vm_storage_container_name: machines

# nutanix_prism_image_storage_container_name is the name of the Storage Container that will be used when uploading the ISO to the Image Configuration service
nutanix_prism_image_storage_container_name: images

######################### Nutanix CSI Deployment Role Variables
### General Nutanix CSI Operator Configuration
nutanix_csi_prism_hostname: "{{ nutanix_prism_hostname }}"
nutanix_csi_prism_port: "{{ nutanix_prism_port }}"
nutanix_csi_prism_username: "{{ nutanix_prism_username }}"
nutanix_csi_prism_password: "{{ nutanix_prism_password }}"

## nutanix_csi_deploy_iscsid_machineconfig is required for the Nutanix Volumes
##  StorageClass to enable the iSCSId SystemD Service to bind the PVCs to the Pods
nutanix_csi_deploy_iscsid_machineconfig: true

### Nutanix Volumes StorageClass, iSCSI based, no RWX
nutanix_csi_deploy_volumes_storageclass: true
nutanix_csi_volumes_storage_container_name: "{{ nutanix_prism_vm_storage_container_name }}"
nutanix_csi_volumes_dataservices_ip: 1.2.3.4

### Nutanix Files StorageClass, NFS Based, RWO and RWX supported
#### Assumes the NFS Store has All Users Squashed to nobody:nobody (65534:65534)
nutanix_csi_deploy_files_storageclass: false
nutanix_csi_files_nfs_server: 5.6.7.8
nutanix_csi_files_nfs_path: /sharePath

######################### General Variables, no need to edit
nutanix_prism_endpoint: "https://{{ nutanix_prism_hostname }}:{{ nutanix_prism_port }}"
nutanix_prism_api_v3_base: "/api/nutanix/v3"
nutanix_prism_api_v2_base: "/PrismGateway/services/rest/v2.0"